
/*
 * 
 * (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
 *
 *
 */

/*   This should be autogenerated  */
#ifndef __RWLOGD_CLI_SINK_HPP__
#define __RWLOGD_CLI_SINK_HPP__

#include "rwlogd_sink_common.hpp"
#include "rwlogd_common.h"
#define RWLOGD_CLI_SINK_REGISTER (_sink_sufix) \
    do { \
      sink_conn = rwlogd_create_sink_ ## _sink_sufix(); \
      TAILQ_INSERT_TAIL(rwlogd_instance_data->sink_list, sink_conn); \
    } while (0)

#endif
