language: c
compiler:
  - gcc
  - clang

before_install: ./.travis/prepare.sh

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=3.18.1
  - TESTSUITE=1 OPTS="--enable-shared"
  - BUILD_ENV="-m32" OPTS="--disable-ssl"
  - KERNEL=4.0.2
  - KERNEL=3.17.7 DPDK=1
  - KERNEL=3.17.7 DPDK=1 OPTS="--enable-shared"
  - KERNEL=3.17.7
  - KERNEL=3.16.7
  - KERNEL=3.14.27
  - KERNEL=3.12.35
  - KERNEL=3.10.63
  - KERNEL=3.4.105
  - KERNEL=2.6.32.65

script: ./.travis/build.sh $OPTS

notifications:
  email:
    recipients:
      - secure: KnZ6yDXDcC4VoiI04ZYR4sRTln7q16aXA7gVBa/M1jPWxl3BiTi+4idVE5bgrB1AK5iUwUXN6LQpjOdFDw1U/D+sKt+xmVG5MyLaTYIFp1TUOgtSGeiG3IUhpu125PN1i2EhXNqANyWyStCiISDvJkDe4D/tbBehip1AEBuQONk=
