#!/bin/bash


if [ $# -lt 1 ]; then
    echo 'args are system [command [args...]]'
    exit 1
fi

if [ -z "$RIFT_ROOT" ]; then
    echo "this tool is meant to be run from inside a rift-shell"
    exit 1
fi

if ! [[ $RIFT_ROOT =~ /net/[a-z0-9]+/localdisk/ ]]; then
    echo 'RIFT_ROOT is not a system independent path (/net/system/localdisk/,,,,)'
    exit 1
fi


system=$1
shift
ssh $system /usr/rift/bin/setview $RIFT_ROOT "$@"
