#!/bin/bash

if [ $# -lt 1 ]; then
	echo $0: 'args are system/ip [cmd [args...]]'
	exit 1
fi

if [ "$1" == "auto" ]; then
    sys=`${RIFT_ROOT:-/usr/rift}/scripts/env/getmyvms 1`
else
    sys=$1
fi
shift
if [ $# -eq 0 ]; then
	term="-tt"
else
	term=""
fi
chmod 600 ${RIFT_ROOT:-/usr/rift}/scripts/vm/home/rift/.ssh/id_rsa
exec ssh $term -i ${RIFT_ROOT:-/usr/rift}/scripts/vm/home/rift/.ssh/id_rsa rift@$sys  "$@"




