#!/bin/bash

# 
# (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
#

term=""
if [ "$1" == "-n" ]; then
    term="-n"
    shift
fi

if [ $# -lt 1 ]; then
	echo $0: 'args are system/ip [cmd [args...]]'
	exit 1
fi

if [ "$1" == "auto" ]; then
    sys=`${RIFT_ROOT:-/usr/rift}/scripts/env/getmyvms 1`
else
    sys=$1
fi
shift

if [ ! -f ~/.ssh/id_grunt ]; then
    cp `dirname $0`/id_grunt ~/.ssh/id_grunt
    chmod 600 ~/.ssh/id_grunt
fi
if [ $# -eq 0 ]; then
	term="$term -tt"
fi
exec ssh $term -i ~/.ssh/id_grunt -o StrictHostKeyChecking=no root@$sys "$@"



