language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install mock unittest2


before_script: python setup.py pep8
script: python setup.py test

notifications:
  email:
    - tomaz+travisci@tomaz.me
    - ilgizisl@gmail.com
