#!/bin/bash
# 
# (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
#
# Author(s): Paul Laidler
# Creation Date: 2016/01/04
#
source $RIFT_INSTALL/usr/rift/systemtest/util/mano/mano_common.sh

SCRIPT_TEST="py.test -x -v \
            ${PYTEST_DIR}/mission_control/test_mission_control.py \
            ${PYTEST_DIR}/mission_control/launchpad/test_launchpad_longevity.py"

test_prefix="launchpad_longevity_systest"
test_cmd=""
repeat=10
repeat_keyword="longevity"
repeat_system=1

# Parse commonline argument and set test variables
parse_args "${@}"

# Construct the test command based on the test variables
construct_test_comand

# Execute from pytest root directory to pick up conftest.py
cd "${PYTEST_DIR}"

test_rc=0
for i in $(seq ${repeat_system});
do
	echo "CYCLE: $i"
	eval ${test_cmd}
	test_rc=$?
	echo "DEBUG: Got test command rc: $test_rc"
	if [[ ${test_rc} -ne 0 ]]; then
		echo "Exiting with test_rc: $test_rc"
		break
	 fi
done

# unit test XML files are converted to pretty printed format
pretty_print_junit_xml

exit ${test_rc}
