#!/bin/bash
# 
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Author(s): Paul Laidler
# Creation Date: 2016/07/12
#

source $RIFT_INSTALL/usr/rift/systemtest/util/mano/mano_common.sh
SCRIPT_TEST="py.test -x -v ${PYTEST_DIR}/rift/basic/basic.py"
test_cmd=""
parse_args "${@}"
construct_test_command
cd "${PYTEST_DIR}"
eval ${test_cmd}
