#!/bin/bash

if [ -z "$RIFT_INSTALL" ]; then
   rift_install="/"
else
   rift_install=$RIFT_INSTALL
fi

zsh_bin="/usr/bin/zsh"
zsh_cmd=${zsh_bin}
test_name=""

if [ -z "${RIFT_MODULE_PATH}" ]; then
  echo "WARNING: RIFT_MODULE_PATH not found. Setting to a reasonable default."
  export RIFT_MODULE_PATH="/usr/lib64/zsh/5.0.7:$RIFT_INSTALL/usr/lib/zsh/5.0.7"
fi

while [[ $# > 0 ]]
do
  arg=$1
  case $arg in
    --trace_level | --netconf_host | --netconf_port | --username | --passwd)
      zsh_cmd="${zsh_cmd} $1 $2"
      shift 2
    ;;
    --netconf)
      if [ -n "${rwmsg}" ]; then
         echo "Netconf mode and rwmsg mode cannot be specified together"
         exit 1
      fi
      netconf=1
      shift
    ;;
    --rwmsg)
      if [ -n "${netconf}" ]; then
         echo "Netconf mode and rwmsg mode cannot be specified together"
         exit 1
      fi
      rwmsg=1
      zsh_cmd="${zsh_cmd} --rwmsg"
      shift
    ;;
    --help)
      show_help=1
      shift
    ;;
    -c)
      quoted_cmd=$2
      shift 2
    ;;
    --test-name)
      test_name=$2
      shift 2
    ;;
    --rift_var_root)
      if [ ! -d "$2" ]; then 
         echo "RIFT_VAR_ROOT '$2' not found"
         exit 1
      fi
      export RIFT_VAR_ROOT="$2"
      shift 2
    ;;

    *)
     echo "Error Unknown option $arg to rwcli"
     exit 1
  esac
done

if [ -n "${show_help}" ]; then
   zsh_cmd="${zsh_bin} --help"
   ${zsh_cmd}
   echo "  --test-name      NAME	Test Name with which Riftware was launched"
   exit 0
fi

if [ -z "${RIFT_VAR_ROOT}" ]; then
  # Get the rift-var-root
  if [ -z ${test_name} ]
  then
    rift_var_root=$(rwyangutil --get-rift-var-root)
  else
    rift_var_root=$(rwyangutil --get-rift-var-root test-name:$test_name)
  fi
  rc=$?
  if [ $rc -ne 0 ]; then
    # Unable to set rift_var_root
    exit 1
  else
    export RIFT_VAR_ROOT=${rift_var_root}
  fi
fi

if [ -z "${quoted_cmd}" ]; then
  echo ${zsh_cmd}
  exec ${zsh_cmd}
else
  echo ${zsh_cmd} -c \"${quoted_cmd}\"
  exec ${zsh_cmd} -c "${quoted_cmd}"
fi
