#!/bin/bash
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
# 3 July 2016 -- Jeremy Mordkoff -- Added Ubuntu Support
# 6 July 2016 -- Jeremy Mordkoff -- Fixed install lists, code moved from enable_lab

if python3 -mplatform | grep -qi ubuntu; then
    apt-get update
	apt-get -y install nfs-kernel-server autofs net-tools rpcbind
	sed -i 's/#\/net/\/net/' /etc/auto.master 
else
	yum install -y autofs nfs-utils rpcbind net-tools 
	cp /usr/rift/setup/skel/etc/nfsmount.conf /etc/nfsmount.conf
fi

if ! grep -q localdisk /etc/exports; then
	echo "/localdisk *(rw,no_root_squash)" >>/etc/exports
fi
systemctl enable nfs-server
systemctl enable autofs
systemctl restart nfs-server
systemctl restart autofs



