#!/bin/bash
# 
#   Copyright 2016-2017 RIFT.io Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Author(s): Jeremy Mordkoff, Lezz Giles
# Creation Date: 08/29/2016
# 3-Mar-2017 -- JLM -- removed remaining cruft related to FC20 support
# 
# This script tries to follow https://google.github.io/styleguide/shell.xml
#

# This is a top-level installer for the RIFT.io launchpad
#
# Arguments and options: use -h or --help
#
# dependencies -- requires sudo rights

# Defensive bash programming flags
set -o errexit    # Exit on any error
trap 'echo "ERROR: Command failed at $BASH_SOURCE:$LINENO: \"$BASH_COMMAND\"" >&2' ERR

set -o nounset    # Expanding an unset variable is an error.  Variables must be
                  # set before they can be used.

###############################################################################
# Options and arguments

params="$(getopt -o h -l help --name "$0" -- "$@")"
if [ $? != 0 ] ; then
    echo "Failed parsing options." >&2
    exit 1
fi

eval set -- $params

usage() 
{

	    echo
	    echo "NAME:"
	    echo "  $0"
	    echo
	    echo "SYNOPSIS:"
	    echo "  $0 -h|--help"
	    echo "  $0 [--rift] [<LAUNCHPAD_REPOSITORY> [<LAUNCHPAD_VERSION>]]"
	    echo
	    echo "DESCRIPTION:"
	    echo "  Prepare current system to run launchpad as a service."
	    echo "  LAUNCHPAD_REPOSITORY (optional): name of the RIFT.ware repository."
	    echo "  LAUNCHPAD_VERSION (optional): version of the platform packages to be installed."
        echo "  --rift causes the installer to use the RIFT mirrors where available"
	    echo


}

use_rift_mirrors=false
while true; do
    case "$1" in
	-h|--help) usage; exit 0;;
    --rift) use_rift_mirrors=true;;
	--) shift; break;;
	*) echo "Not implemented: $1" >&2; usage; exit 1;;
    esac
done

###############################################################################
# Find the platform

if grep -qi "Ubuntu 16.04" /etc/issue; then
    readonly PLATFORM=ub16
else
    echo "This installer only runs on Ubuntu 16.04." >&2
    exit 1
fi

# Check the wordsize
arch=`arch`
if [[ $arch != x86_64 ]]; then
    echo "You can only install RIFT.ware on a 64-bit platform, but this platform is not 64-bit"
    exit 1
fi

###############################################################################
# Set up repo and version

readonly PLATFORM_REPOSITORY=${1:-release}
readonly PLATFORM_VERSION=${2:-4.3.3.1.52691}

cat <<EOF

================================================================================================
Installing RIFT.ware Launchpad version $PLATFORM_VERSION from repository $PLATFORM_REPOSITORY
================================================================================================

EOF

# enable the right repos
curl http://repos.riftio.com/public/xenial-riftware-public-key | sudo apt-key add -
sudo curl -o /etc/apt/sources.list.d/RIFT.list http://buildtracker.riftio.com/repo_file/ub16/${PLATFORM_REPOSITORY}/ 
sudo apt-get update
        
# and install the RIFT container tools
sudo apt-get remove -y rw.tools-container-tools rw.tools-scripts
sudo apt-get install -y rw.tools-container-tools=${PLATFORM_VERSION} rw.tools-scripts=${PLATFORM_VERSION}
    
# Install all required packages; this includes the RIFT platform code and tools
# and install of the packages required to run launchpad.
flags=""
if $use_rift_mirrors; then
    flags="$flags --rift"
fi
sudo /usr/rift/container_tools/mkcontainer $flags --modes launchpad --repo ${PLATFORM_REPOSITORY} --rw-version ${PLATFORM_VERSION}

