#!/bin/bash

SYS_TEST=$RIFT_INSTALL/usr/rift/systemtest/
PYTEST_DIR=$SYS_TEST/notification_test/pytest

TEST_NAME="TC_NOTIFICATION_TEST"
RESULT_XML="notification_test.xml"

test_args="\
    --junitprefix ${TEST_NAME} \
    --junitxml ${RIFT_MODULE_TEST}/${RESULT_XML}"

TEST_CMD="py.test -v ${PYTEST_DIR}/notification_test.py ${test_args} "

$TEST_CMD
