language: ruby

branches:
  only:
    - master

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode

gemfile:
  - .travis/Gemfile

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1
  matrix:
    - conn=ruby      REDIS_BRANCH=2.6
    - conn=hiredis   REDIS_BRANCH=2.6
    - conn=synchrony REDIS_BRANCH=2.6
    - conn=ruby      REDIS_BRANCH=2.8
    - conn=ruby      REDIS_BRANCH=unstable

matrix:
  exclude:
    # hiredis
    - rvm: jruby-18mode
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=2.6
    - rvm: jruby-19mode
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=2.6

    # synchrony
    - rvm: 1.8.7
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=2.6
    - rvm: jruby-18mode
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=2.6
    - rvm: jruby-19mode
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=2.6

notifications:
  irc:
    - irc.freenode.net#redis-rb
  email:
    - damian.janowski@gmail.com
    - pcnoordhuis@gmail.com
