#!/bin/bash

source $RIFT_INSTALL/usr/rift/systemtest/util/mano/mano_common.sh

SYS_TEST=$RIFT_INSTALL/usr/rift/systemtest/
PYTEST_DIR=$SYS_TEST/cal_module_test/pytest
SCRIPT_TEST="py.test -x -v -p no:cacheprovider ${PYTEST_DIR}/cal_module_test.py"
test_prefix="cal_module_test"
TEST_NAME="TC_CAL_MODULE_TEST"
RESULT_XML="cal_module_test.xml"

parse_args "${@}"
test_cmd="${SCRIPT_TEST}"
append_args test_cmd os-host "\"${cloud_host}\""
append_args test_cmd os-user "\"${user}\""
append_args test_cmd os-tenant ${tenant[0]}
append_args test_cmd junitprefix "\"${TEST_NAME}\""
append_args test_cmd junitxml "\"${RIFT_MODULE_TEST}/${RESULT_XML}\""

cd "${PYTEST_DIR}"
eval ${test_cmd}

