#!/bin/bash


yum -y install wget
mkdir rift
cd rift
wget -O - http://repo.riftio.com/releases/open.riftio.com/OSM/mkvmimg.tar | tar xf -
bash ./mkvmimg --container --modes build
echo Container is now ready to build RIFT.ware
# got clone ...
# cd  ....
# make build
