#! /bin/bash

# 
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Author(s): Anil Gunturu
# Creation Date: 07/24/2014
# 

##
# This script is used to copy the riftware software into the qcow image
# This script must be run on the grunt machine as root
##

if ! [ $# -eq 2 ]; then
    echo "Usage: $0 <rft root> <image-path>"
    echo "       Example:"
    echo "       $0 /net/charm/localdisk/jeipe/workworld/rift /root/rwkvm/rwkvm_grunt16_vm1/rwkvm_grunt16_vm1.qcow2"
    exit 1
fi

# This script should only be excuted on grunt machines
if [[ ! `hostname` =~ grunt[0-9]*.* ]]; then
  echo "Current hostname `hostname`"
  echo "Run this script on only grunt machines"
  echo "Exiting..."
  exit 1
fi

# Must be root to execute this script
if [[ ! `whoami` = "root" ]]; then
  echo "You are `whoami`"
  echo "Must be root to execute this script"
  echo "Exiting..."
  exit 1
fi

pushd $DIR/$1 > /dev/null

  if [ ! -e /usr/lib64/guestfs/supermin.d/00-dir ]; then
    cat > /usr/lib64/guestfs/supermin.d/00-dir <<EOF
/
/net
/net/boson
/net/boson/usr
/net/boson/usr/local
/net/boson/usr/local/fedora
EOF

  fi

  if  [ -d /root/rw_tmp_mnt ]; then
    echo "/root/rw_tmp_mnt directory exists - deleting..!!"
    umount /root/rw_tmp_mnt
    rmdir /root/rw_tmp_mnt
  fi

  mkdir /root/rw_tmp_mnt
  guestmount -a $2 -m /dev/sda1 /root/rw_tmp_mnt
  cd /root/rw_tmp_mnt
  cd opt
  mkdir riftware
  cd riftware
  cp -R $1/.install/usr .
  umount /root/rw_tmp_mnt
popd > /dev/null

