#! /bin/bash

# RIFT_IO_STANDARD_COPYRIGHT_HEADER(BEGIN)
# Creation Date: 06/17/2015
# RIFT_IO_STANDARD_COPYRIGHT_HEADER(END)

# This script is used for installation of VMs for
# the demo1 setup
#Should be run on the controller node - 10.66.4.101

set -e

function print_usage() {
    echo "Usage: $0"
    echo "       Optional arguments"
    echo "       -l|--launch-vms Launch VMs"
    echo "       -d|--delete-vms Delete VMs"
    echo "       -s|--setup Setup quotas and flavors"
    echo "       -c|--cleanup Delete quotas and flavors"
    echo "       -k|--launch-1b-vms"
    echo "       -o|--launch-1a-vms"
    echo "       -m|--delete-1a-vms"
    echo "       -n|--delete-1b-vms"
    exit 1
}

##
# Specifically deletes flavors etc
##
function cleanup() {

 

         # delete all flavors
         $CLOUDTOOL flavor list | grep 'rw.' | awk '{print \$1}' |
         while read f; do
             echo Deleting flavor \$f
             $CLOUDTOOL flavor delete -n \$f
         done
	 #Delete hostagg
         $CLOUDTOOL hostagg delete -n rw.hostagg.1a_tg -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.1a_lb1 -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.1a_lb2 -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.1a_ts -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.4_vnf -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.demo_mg -f	 

         $CLOUDTOOL hostagg delete -n rw.hostagg.1b_tg -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.1b_lb1 -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.1b_lb2 -f	 
         $CLOUDTOOL hostagg delete -n rw.hostagg.1b_ts -f	 
}


##
# This function setups openstack quotas and flavors
##
function setup() {
    # Setup quotas and flavors


        # install the vm image
        if ! $CLOUDTOOL image getid -n $IMAGENAME; then
          echo 'install image'
          $CLOUDTOOL image create -n $IMAGENAME -f $IMAGEFILE
        fi

        #cpuset quotas
        echo 'Setting quotas'
        $CLOUDTOOL quota set --project demo --memory 1086432 --vcpus 500 --vms 64 --ips 64
        . /home/stack/devstack/accrc/admin/admin
        tenant_id=`keystone tenant-list  | awk '/demo/ { print $2; }'`	
        neutron quota-update --tenant-id $tenant_id --port 250 --network 20 --subnet 20
			
        #Create networks
        echo 'Creating networks'
        for nw in "private2 11.0.0.0 physnet2" "private3 12.0.0.0 physnet3" "private4 13.0.0.0 physnet4" "private5 14.0.0.0 physnet5" "private6 15.0.0.0 physnet6"; do
            set $nw
            if ! neutron net-list | grep -q $1; then
                neutron net-create --tenant-id $tenant_id --provider:physical_network=$3 --provider:network_type=flat $1
                neutron subnet-create --tenant-id $tenant_id $1 $2/24 --name ${1}_subnet --ip_version 4 --disable-dhcp
            fi
        done

        for nw in "virtnet1 17.0.0.0" "virtnet2 18.0.0.0"; do
          set $nw
          if ! neutron net-list | grep -q $1; then
              neutron net-create --tenant-id $tenant_id $1
              neutron subnet-create --tenant-id $tenant_id $1 $2/8 --name ${1}_subnet --dns-nameservers list=true 10.66.0.1
          fi
        done
	      
        # set rules
        echo 'Setting rules'
        $CLOUDTOOL rules set || true

        #create hostaggregates
        $CLOUDTOOL hostagg create -n rw.hostagg.1a_tg -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1a_tg -d DEMO_1A_TG=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1a_tg -c grunt107.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.1a_lb1 -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1a_lb1 -d DEMO_1A_LB1=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1a_lb1 -c grunt108.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.1a_lb2 -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1a_lb2 -d DEMO_1A_LB2=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1a_lb2 -c grunt109.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.1a_ts -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1a_ts -d DEMO_1A_TS=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1a_ts -c grunt110.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.demo_mg -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.demo_mg -d DEMO_MG=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.demo_mg -c grunt106.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.4_vnf -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.4_vnf -d DEMO_4_VNF=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.4_vnf -c grunt101.lab.riftio.com
		
        $CLOUDTOOL flavor create -n rw.demo_1a_tg -m 16384 -d 10 -v 2 -B large -e DEMO_1A_TG=1  
        $CLOUDTOOL flavor create -n rw.demo_1a_ts -m 16384 -d 10 -v 2 -B large -e DEMO_1A_TS=1  
        $CLOUDTOOL flavor create -n rw.demo_1a_lb1 -m 16384 -d 10 -v 2 -B large -e DEMO_1A_LB1=1 
        $CLOUDTOOL flavor create -n rw.demo_1a_lb2 -m 16384 -d 10 -v 2 -B large -e DEMO_1A_LB2=1 
        $CLOUDTOOL flavor create -n rw.demo_mgmt -m 16384 -d 10 -v 2 -e DEMO_MG=1
        $CLOUDTOOL flavor create -n rw.wag.app -m 8192 -d 10 -v 4 -e DEMO_4_VNF=1 
        $CLOUDTOOL flavor create -n rw.wag.vnf -m 32768 -d 20 -v 4 -e DEMO_4_VNF=1


        $CLOUDTOOL hostagg create -n rw.hostagg.1b_tg -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1b_tg -d DEMO_1B_TG=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1b_tg -c grunt102.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.1b_lb1 -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1b_lb1 -d DEMO_1B_LB1=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1b_lb1 -c grunt103.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.1b_lb2 -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1b_lb2 -d DEMO_1B_LB2=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1b_lb2 -c grunt104.lab.riftio.com
        $CLOUDTOOL hostagg create -n rw.hostagg.1b_ts -a nova
        $CLOUDTOOL hostagg setmetadata -n rw.hostagg.1b_ts -d DEMO_1B_TS=1
        $CLOUDTOOL hostagg addhost -n rw.hostagg.1b_ts -c grunt105.lab.riftio.com
		
        $CLOUDTOOL flavor create -n rw.demo_1b_tg -m 16384 -d 10 -v 2 -B large -D -T 1 -e DEMO_1B_TG=1  
        $CLOUDTOOL flavor create -n rw.demo_1b_ts -m 16384 -d 10 -v 2 -B large -D -T 1 -e DEMO_1B_TS=1  
        $CLOUDTOOL flavor create -n rw.demo_1b_lb1 -m 16384 -d 10 -v 2 -B large -D -T 1 -e DEMO_1B_LB1=1 
        $CLOUDTOOL flavor create -n rw.demo_1b_lb2 -m 16384 -d 10 -v 2 -B large -D -T 1 -e DEMO_1B_LB2=1 
}

##
# This function lauches the VMs
##

function launch_vms() {
    # Launch the VMs 
    launch_1a_vms
    launch_1b_vms 

}


function launch_1a_vms() {
    # Launch the VMs 
        $CLOUDTOOL vm create -n rw_1a_tg_lead_vm -i $IMAGENAME -f rw.demo_1a_tg -s -N 'private,private2'
        $CLOUDTOOL vm create -n rw_1a_tg_vm1 -i $IMAGENAME -f rw.demo_1a_tg -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_tg_vm2 -i $IMAGENAME -f rw.demo_1a_tg -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_tg_vm3 -i $IMAGENAME -f rw.demo_1a_tg -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_tg_vm4 -i $IMAGENAME -f rw.demo_1a_tg -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_lb_lead_vm -i $IMAGENAME -f rw.demo_1a_lb1 -s -N 'private,private2' 
        $CLOUDTOOL vm create -n rw_1a_lb1_vm1 -i $IMAGENAME -f rw.demo_1a_lb1 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_lb2_vm1 -i $IMAGENAME -f rw.demo_1a_lb2 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_lb1_vm2 -i $IMAGENAME -f rw.demo_1a_lb1 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_lb2_vm2 -i $IMAGENAME -f rw.demo_1a_lb2 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_lb1_vm3 -i $IMAGENAME -f rw.demo_1a_lb1 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_lb2_vm3 -i $IMAGENAME -f rw.demo_1a_lb2 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_lb1_vm4 -i $IMAGENAME -f rw.demo_1a_lb1 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_lb2_vm4 -i $IMAGENAME -f rw.demo_1a_lb2 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_ts_lead_vm -i $IMAGENAME -f rw.demo_1a_ts -s -N 'private,private2' 
        $CLOUDTOOL vm create -n rw_1a_ts_vm1 -i $IMAGENAME -f rw.demo_1a_ts -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_ts_vm2 -i $IMAGENAME -f rw.demo_1a_ts -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1a_ts_vm3 -i $IMAGENAME -f rw.demo_1a_ts -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_ts_vm4 -i $IMAGENAME -f rw.demo_1a_ts -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1a_cli_vm -i $IMAGENAME -f rw.demo_mgmt -s -N 'private' 
        $CLOUDTOOL vm create -n rw_1a_mgmt_vm -i $IMAGENAME -f rw.demo_mgmt -s -N 'private' 
        $CLOUDTOOL vm create -n rw_wag_app_vm -i $IMAGENAME -f rw.wag.app -s -N 'private,virtnet1,virtnet2' 
        $CLOUDTOOL vm create -n rw_wag_vnf_vm -i $IMAGENAME -f rw.wag.vnf -s -N 'private,virtnet1,virtnet2' 

        sleep 15
        $DO_CLOUD /usr/rift/scripts/cloud/enable_lab
}

function launch_1b_vms() {
    # Launch the VMs 
        $CLOUDTOOL vm create -n rw_1b_tg_lead_vm -i $IMAGENAME -f rw.demo_1b_tg -s -N 'private,private2'
        $CLOUDTOOL vm create -n rw_1b_tg_vm1 -i $IMAGENAME -f rw.demo_1b_tg -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_tg_vm2 -i $IMAGENAME -f rw.demo_1b_tg -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_tg_vm3 -i $IMAGENAME -f rw.demo_1b_tg -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_tg_vm4 -i $IMAGENAME -f rw.demo_1b_tg -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_lb_lead_vm -i $IMAGENAME -f rw.demo_1b_lb1 -s -N 'private,private2' 
        $CLOUDTOOL vm create -n rw_1b_lb1_vm1 -i $IMAGENAME -f rw.demo_1b_lb1 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_lb2_vm1 -i $IMAGENAME -f rw.demo_1b_lb2 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_lb1_vm2 -i $IMAGENAME -f rw.demo_1b_lb1 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_lb2_vm2 -i $IMAGENAME -f rw.demo_1b_lb2 -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_lb1_vm3 -i $IMAGENAME -f rw.demo_1b_lb1 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_lb2_vm3 -i $IMAGENAME -f rw.demo_1b_lb2 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_lb1_vm4 -i $IMAGENAME -f rw.demo_1b_lb1 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_lb2_vm4 -i $IMAGENAME -f rw.demo_1b_lb2 -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_ts_lead_vm -i $IMAGENAME -f rw.demo_1b_ts -s -N 'private,private2' 
        $CLOUDTOOL vm create -n rw_1b_ts_vm1 -i $IMAGENAME -f rw.demo_1b_ts -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_ts_vm2 -i $IMAGENAME -f rw.demo_1b_ts -s -N 'private,private2,private3,private4' 
        $CLOUDTOOL vm create -n rw_1b_ts_vm3 -i $IMAGENAME -f rw.demo_1b_ts -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_ts_vm4 -i $IMAGENAME -f rw.demo_1b_ts -s -N 'private,private2,private5,private6' 
        $CLOUDTOOL vm create -n rw_1b_cli_vm -i $IMAGENAME -f rw.demo_mgmt -s -N 'private' 
        $CLOUDTOOL vm create -n rw_1b_mgmt_vm -i $IMAGENAME -f rw.demo_mgmt -s -N 'private' 

        sleep 15
        $DO_CLOUD /usr/rift/scripts/cloud/enable_lab
}

function delete_vms() {
        delete_1a_vms
        delete_1b_vms
}

function delete_1a_vms() {
        $CLOUDTOOL vm destroy -n rw_1a_tg_lead_vm 
        $CLOUDTOOL vm destroy -n rw_1a_tg_vm1 
        $CLOUDTOOL vm destroy -n rw_1a_tg_vm2 
        $CLOUDTOOL vm destroy -n rw_1a_tg_vm3 
        $CLOUDTOOL vm destroy -n rw_1a_tg_vm4 
        $CLOUDTOOL vm destroy -n rw_1a_lb_lead_vm 
        $CLOUDTOOL vm destroy -n rw_1a_lb1_vm1 
        $CLOUDTOOL vm destroy -n rw_1a_lb2_vm1 
        $CLOUDTOOL vm destroy -n rw_1a_lb1_vm2 
        $CLOUDTOOL vm destroy -n rw_1a_lb2_vm2 
        $CLOUDTOOL vm destroy -n rw_1a_lb1_vm3 
        $CLOUDTOOL vm destroy -n rw_1a_lb2_vm3 
        $CLOUDTOOL vm destroy -n rw_1a_lb1_vm4 
        $CLOUDTOOL vm destroy -n rw_1a_lb2_vm4 
        $CLOUDTOOL vm destroy -n rw_1a_ts_lead_vm 
        $CLOUDTOOL vm destroy -n rw_1a_ts_vm1
        $CLOUDTOOL vm destroy -n rw_1a_ts_vm2
        $CLOUDTOOL vm destroy -n rw_1a_ts_vm3
        $CLOUDTOOL vm destroy -n rw_1a_ts_vm4
        $CLOUDTOOL vm destroy -n rw_1a_cli_vm 
        $CLOUDTOOL vm destroy -n rw_1a_mgmt_vm
        $CLOUDTOOL vm destroy -n rw_wag_app_vm
        $CLOUDTOOL vm destroy -n rw_wag_vnf_vm 
}

function delete_1b_vms() {
        $CLOUDTOOL vm destroy -n rw_1b_tg_lead_vm 
        $CLOUDTOOL vm destroy -n rw_1b_tg_vm1 
        $CLOUDTOOL vm destroy -n rw_1b_tg_vm2 
        $CLOUDTOOL vm destroy -n rw_1b_tg_vm3 
        $CLOUDTOOL vm destroy -n rw_1b_tg_vm4 
        $CLOUDTOOL vm destroy -n rw_1b_lb_lead_vm 
        $CLOUDTOOL vm destroy -n rw_1b_lb1_vm1 
        $CLOUDTOOL vm destroy -n rw_1b_lb2_vm1 
        $CLOUDTOOL vm destroy -n rw_1b_lb1_vm2 
        $CLOUDTOOL vm destroy -n rw_1b_lb2_vm2 
        $CLOUDTOOL vm destroy -n rw_1b_lb1_vm3 
        $CLOUDTOOL vm destroy -n rw_1b_lb2_vm3 
        $CLOUDTOOL vm destroy -n rw_1b_lb1_vm4 
        $CLOUDTOOL vm destroy -n rw_1b_lb2_vm4 
        $CLOUDTOOL vm destroy -n rw_1b_ts_lead_vm 
        $CLOUDTOOL vm destroy -n rw_1b_ts_vm1
        $CLOUDTOOL vm destroy -n rw_1b_ts_vm2
        $CLOUDTOOL vm destroy -n rw_1b_ts_vm3
        $CLOUDTOOL vm destroy -n rw_1b_ts_vm4
        $CLOUDTOOL vm destroy -n rw_1b_cli_vm 
        $CLOUDTOOL vm destroy -n rw_1b_mgmt_vm

}

# Specify the controller node
CONTROLLER_NODE=10.66.4.101

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#CLOUDTOOL=$BASEDIR/cloudtool
CLOUDTOOL=/usr/rift/scripts/cloud/cloudtool
IMAGENAME=rwopenstack_vm
IMAGEFILE=/net/boson/home1/common/vm/rift-root-latest.qcow2
SSH_ROOT=/usr/rift/bin/ssh_root
DO_CLOUD=/usr/rift/scripts/cloud/docloud
LAUNCH_VMS=false
LAUNCH_1A_VMS=false
LAUNCH_1B_VMS=false
DELETE_VMS=false
DELETE_1A_VMS=false
DELETE_1B_VMS=false
SETUP=false
CLEANUP=false

##
# Parse options
##
while [[ $# > 0 ]]
do
key="$1"
shift
case $key in
    -l|--launch-vms)
    LAUNCH_VMS=true
    ;;
    -o|--launch-1a-vms)
    LAUNCH_1A_VMS=true
    ;;
    -k|--launch-1b-vms)
    LAUNCH_1B_VMS=true
    ;;
    -d|--delete-vms)
    DELETE_VMS=true
    ;;
    -m|--delete-1a-vms)
    DELETE_1A_VMS=true
    ;;
    -n|--delete-1b-vms)
    DELETE_1B_VMS=true
    ;;
    -s|--setup)
    SETUP=true
    ;;
    -c|--cleanup)
    CLEANUP=true
    ;;
    *)
    print_usage
    ;;
esac
done

# done

if $LAUNCH_VMS; then
    launch_vms

elif $LAUNCH_1A_VMS; then
    launch_1a_vms

elif $LAUNCH_1B_VMS; then
    launch_1b_vms

elif $DELETE_VMS; then
    delete_vms

elif $DELETE_1A_VMS; then
    delete_1a_vms

elif $DELETE_1B_VMS; then
    delete_1b_vms

elif $SETUP; then
    setup

elif $CLEANUP; then
    cleanup
fi
