#! /bin/bash

# 
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Author(s): Anil Gunturu
# Creation Date: 07/24/2014
# 

# Since openstack consists of
# many different modules, this script creates a single hash
# from the hashes of individual modules.

TEMPDIR=`pwd`
STACKDIR=$1
cd $STACKDIR
echo "OpenStack Version Information" > VERSION
ls modules/openstack |
    while read d; do
        cd modules/openstack/$d
        echo "modules/openstack/$d `git log -n1 | grep commit | awk '{print $2}'`" >> $STACKDIR/VERSION
       cd $STACKDIR
    done

md5=`md5sum VERSION | awk '{print $1}'`
mv VERSION VERSION.$md5
cd $TEMPDIR
