#!/bin/bash 

# this script should be run on the openstack controller node
# the argument is the compute node host name

HOST=$1
TENANT=${2:-demo}


. /root/keystonerc_admin
IDS="`nova list --all-tenants --host $HOST | grep rwopenstack | cut -f2 -d\  `"
echo "Found these VMs on $HOST - $IDS"


. /root/keystonerc_$TENANT
for id in $IDS; do
    echo "starting $id as $TENANT"
    nova rboot --hard $id
done

