language: erlang

env:
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2

before_install:
  - sudo apt-get install $LUA

script:
  - $LUA run_unit_tests.lua
  - $LUA run_functional_tests.lua

notifications:
  email:
    on_success: change
    on_failure: always
