#!/usr/bin/env python

import sys, os, subprocess

if len(sys.argv) == 1:
    import ndl
    testbed = ndl.Testbed()
    controllers = testbed.get_controllers()
else:
    controllers = sys.argv[1:]


IMAGE="/net/boson/home1/common/vm/rift-root-current.qcow2"
hash=os.readlink(IMAGE)

print "deploying %s (%s) to %s" % ( IMAGE, hash, ",".join(controllers) )

def cloudtool(host, *args):
    if 'RIFT_ROOT' in os.environ:
        c = ["ssh", host, "%s/rift-shell" % os.environ['RIFT_ROOT'], "--",  "%s/scripts/cloud/cloudtool" % os.environ['RIFT_ROOT'] ]
    else:
        c = ["ssh", host, "/usr/rift/scripts/cloud/cloudtool" ]
    c = c + list(args)
    print "#######\n# %s\n#######" % " ".join(c)
    return subprocess.check_output(c)

def ssh_root(cmdlist):
    c = [ "ssh", "-o", "StrictHostKeyChecking=no", "-i", "%s/.ssh/id_grunt" % os.environ['HOME'] ] + cmdlist 
    subprocess.call(c)
    
for c in controllers:
    print c
    try:
        cloudtool(c, "-u", "admin", "image", "delete", "-n", "rwopenstack_vm")
    except:
        pass
    cloudtool(c, "image", "create", "-n", "rwopenstack_image", "-f", "/net/boson/home1/common/vm/rift-root-current.qcow2")
    
    
    
