#!/usr/bin/env python

import sys, os, subprocess, time

if len(sys.argv) == 1:
    import ndl
    testbed = ndl.Testbed()
    controllers = testbed.get_controllers()
else:
    controllers = sys.argv[1:]



print "### scanning VMs on %s" % ( ",".join(controllers) )


def cloudtool(host, *args):
    if 'RIFT_ROOT' in os.environ:
        c = ["ssh", host, "/usr/rift/bin/setview", os.environ['RIFT_ROOT'], "./scripts/cloud/cloudtool" ]
    else:
        c = ["ssh", host, "/usr/rift/scripts/cloud/cloudtool" ]
    c = c + list(args)
    print "### " + " ".join(c)
    return subprocess.check_output(c)
    
def get_vm_count(host):
    tries=0
    out=None
    while tries < 5 and out is None:
        tries += 1
        try:
            out = cloudtool(host, "vm", "list" )
        except:
            print "### error from vm list...retrying in one second"
            time.sleep(1)
    out = out.strip()
    if len(out) == 0:
        ct = 0
    else:
        ct = len(out.split('\n'))
    
    print "### %s has %d VMs" % ( host, ct ) 
    return ct

    
for c in controllers:
    out = cloudtool(c, "vm", "list").strip()
    if len(out) == 0:
        print "### NO VMS found on %s" % c
    else:
        for l in out.split('\n'):
            print "#### %s: %s" % (c, l)
    
    
    
