#!/bin/bash 

# this script should be run on the openstack controller node
# the argument is the IP address or name of the VM you are interested in
# the output is a list of the virtual bus ids on the PCI devices and the switch name that 
# they are connected to, one per line
# this all depends on the latest version of grunt_portmap.sh having been run on the grunt


debug=0
if [ "$1" == "-d" ]; then
	debug=1
	shift
fi

if [ $# -ne 1 ]; then
	echo arg is IPAddress
	exit 1
fi

DEBUG() { 
	if [ $debug -eq 1 ]; then
		echo "$*" >&2
	fi
}


IPADDRESS=$1

error() { 
    echo $*
    exit 1
}
if [ -f /root/keystonerc_admin ]; then
	. /root/keystonerc_admin
elif [ -f /home/stack/devstack/accrc/admin/admin ]; then 
	. /home/stack/devstack/accrc/admin/admin
else
	echo "error -- keystone admin rc file not found"
	exit 1
fi


ID=`nova list --all-tenants 1 | egrep "$IPADDRESS[ ;]" | cut -f2 -d\|`
[ -z "$ID" ] && error "no instance with IP Address or name \"$IPADDRESS\" found"

HOST=`nova show $ID | grep 'OS-EXT-SRV-ATTR:hypervisor_hostname' | cut -f3 -d\|`
[ -z "$HOST" ] && error "no HOST found for instance ID \"$ID\""
set $HOST
HOST=$1
echo $HOST

