#!/bin/bash

if [ $# -ne 1 ]; then
    echo arg is compute node name
    exit 
fi

grep CONFIG_MYSQL /root/answers.cfg >/tmp/answers.$$
. /tmp/answers.$$
rm /tmp/answers.$$

HOST=$1
set `host $HOST`
IP=$4


. /root/keystonerc_admin
IDS="`nova list --all-tenants --host $HOST | grep rwopenstack | cut -f2 -d\  `"
for id in $IDS; do
    nova delete $id
done


mysql --user=${CONFIG_MYSQL_USER:-root} --password=${CONFIG_MYSQL_PW} nova<<EOF
delete from compute_nodes where service_id in (select id from services where host='$HOST');
delete from services where host='$HOST';
EOF



perl -i.bak -p -e "s/$IP//g; s/,,+/,/g; s/=,+/=/; s/,$//;" /root/answers.cfg

