#!/bin/bash


export RIFT_ROOT=${RIFT_ROOT:-/usr/rift}

    

# This is rift lab specific but will not be needed once all 
# testbeds have been rebuilt using cobbler
chattr -i /etc/resolv.conf
cat >/etc/resolv.conf <<EOF
search lab.riftio.com. eng.riftio.com. riftio.com.
nameserver 10.64.1.1
nameserver 10.64.1.2
EOF

me=`hostname -s`
controller=${1:-$me}

while ! ping -c 1 $controller; do
    echo "waiting for the network or $controller to come up"
    sleep 1
done
if [ -f /root/keystonerc_admin ]; then
    # we are on the controller
    while ! $RIFT_ROOT/scripts/cloud/neutron_fix_route; do
        echo "neutron fix route failed...retry in 1 second"
        sleep 1
    done
    sleep 1
    /usr/rift/scripts/cloud/restart_by_compute_node `hostname -s`
else
    ssh $controller /usr/rift/scripts/cloud/restart_by_compute_node `hostname -s`
fi

