#!/bin/bash
#
###################################################################
# @Script name:   setbiossetting_intel
###################################################################
VERSION=1.0
# @Description:   This script is to query a Intel server BIOS setting. 
#
# Usage:
#   $0 "bios_setting"
#
# History:
# 5/13/2015: V1.0 (Wei):
#           - 

# 5-13-2015 -- WW

SCRIPT=${0##*\/}

script_fullpath=$(readlink -f $0)
script_dir=$(dirname $script_fullpath)

declare YELLOW='\033[33m'
declare RED='\033[31m'
declare NORMAL='\033[00;00m'
declare GREEN='\033[32m'

get_BIOS=${script_dir}/getbiosseting_intel
#echo full: $script_fullpath
#echo dir: $script_dir
#echo getbios: $get_BIOS

function warn()
{
    _msg=$@
    echo -e "${YELLOW}  -Warn: ${_msg}${NORMAL}"
}

function info()
{
    _msg=$@
    echo -e "${NORMAL}  -Info: ${_msg}"
}

function okinfo()
{
    _msg=$@
    echo -e "${GREEN}  -Info: ${_msg}${NORMAL}"
}

ipmi_passwd="riftIO_ipmi2"
setting=$1
target_value=$2

current_value=$($get_BIOS "$1")
info BIOS setting: -$setting- current value is: $current_value
output=$(syscfg /bcs $ipmi_passwd "$setting" $target_value 2>&1)

if `echo $output | grep -q Successfully`; then
   okinfo BIOS setting: -$setting has been set to $target_value
else
   warn BIOS setting: -$setting failed set to $target_value
fi


