#!/bin/bash -e

# STANDARD_RIFT_IO_COPYRIGHT

# This script recursively shows the status of each submodule that is changed
# check that you are a top level
if [ ! -f .gitmodules ] ; then
    echo "$(basename $0) can only be executed from top (supermodule) level"
    exit 1
fi

echo Changes in supermodule:;
git status -s
echo ""

# Get the status in each submodule that changed
# Itereate through each submodule and show a message if there
# channges to be committed.
# Also show a message if the branch is ahead of origin/master
do_submodule_status() {
        name="$1"
        path="$2"
        toplevel="$3"
        #echo "name= $name  path= $path top= $toplevel" >&2
        cd "$toplevel/$path"

        br=$(git rev-parse --abbrev-ref HEAD)

        if [[ $(git status -s) ]] ; then
                echo Changes in submodule $name on branch $br;
                git status -s; 
                echo '';
        else
                git status | grep -q "Your branch is up-to-date";
                if [[ $? != 0 ]] ; then 
                        echo Changes in submodule $name on branch $br; 
                        git status | grep "Your branch"; 
                        echo ''; 
                fi
        fi
}

export -f do_submodule_status

git submodule foreach --quiet --recursive 'echo "\"$name\" \"$path\" \"$toplevel\""' |
xargs -r -n3 bash -c 'do_submodule_status "$@"' do_submodule_status
