#!/bin/bash -e

# 
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# This script recursively shows the status of each submodule that is changed
# check that you are a top level
if [ ! -f .gitmodules ] ; then
    echo "$(basename $0) can only be executed from top (supermodule) level"
    exit 1
fi

RE1="--- a/(.*)"
RE2="-Subproject commit (.*)"
RE3="\+Subproject commit (.*)"
trap "rm /tmp/xgit-show.$$" 0
trap "exit 1" 2
git show "$@" >/tmp/xgit-show.$$
echo -e "\n================= rift"
cat /tmp/xgit-show.$$
cat /tmp/xgit-show.$$ | while read line; do 
    if [[ $line =~ $RE1 ]]; then
        module=${BASH_REMATCH[1]}
    elif [[ $line =~ $RE2 ]]; then
        start=${BASH_REMATCH[1]}
    elif [[ $line =~ $RE3 ]]; then
        end=${BASH_REMATCH[1]}
        echo -e "\n================= $module"
        pushd $module >/dev/null
        git show $end
        popd >/dev/null
    fi
done
        
