#!/bin/bash
# 
# (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
#
# Author(s): Austin Cormier
# Creation Date: 2014/09/22
#
# Checkout all initialized submodules to the SHA referenced by the superproject.
# Once there, create a local branch as to not be in a detached head state.
#
# Usage: git-xupdate [<submodule>...]

set -o nounset

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/git-common-functions.sh"

function update_submodules_and_attach_local(){
  submodules="$@"
  while read line; do
    if [ "$submodules" != "" ]; then
      if [[ ! "$submodules" =~ "$line" ]]; then
        log "DEBUG - Not updating $line.  Not in submodule list"
        continue;
      fi
    fi

    log "INFO - Updating submodule and attaching local: $line"
    git submodule update "$line"
    if [ $? -ne 0 ]; then
      log "ERROR - Failed to update submodule: $line."
      return 1
    fi

    pushd "$line" >/dev/null
      log "INFO - Setting remote push url on submodule: $line"

      # Extract the current Git push url for the submodule
      current_push_url="$(git remote -v | grep ^origin.*push | cut -f 2 | cut -d " " -f 1)"
      # Replace the default "git:" path with git.eng.riftio.com(burlington)
      new_push_url="${current_push_url/git:/git.eng.riftio.com:}"
      # Set the submodule remote push url to always push to burlington
      git remote set-url --push origin $new_push_url
      if [ $? -ne 0 ]; then
        log "ERROR - Failed to set remote push url on submodule: $line."
        return 1
      fi

      log "INFO - Attaching local branch on submodule: $line"

      git checkout -B local
      if [ $? -ne 0 ]; then
        log "ERROR - Failed to checkout -B local in submodule: $line."
        return 1
      fi
    popd > /dev/null

  done < <(foreach_initialized_submodule)
}

submodules="$@"
## Update the submodules to the revision stored in the
## superproject and attach the local branch to this.
update_submodules_and_attach_local $submodules || exit 1
