#!/bin/bash
# STANDARD_RIFT_IO_COPYRIGHT
# Author(s): Austin Cormier
# Creation Date: 2014/06/05
#
# Ensures that there are no uncommitted/unpushed changes in 
# any of the supermodules or superproject.
#
# Usage: git check-superclean
#
# Check that the superproject and all submodules are completely clean.
# This means no files modified, untracked, unpushed, uncommitted, etc 

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/git-common-functions.sh"

function check_superclean(){
  $DIR/git-check-unpushed
  if [ $? -ne 0 ]; then
    log "ERROR: Unpushed changes in branch: $line"
    return 1
  fi
}

function check_for_unpushed_in_submodules(){
  while read line; do

    pushd $line > /dev/null
      check_superclean || return 1
    popd > /dev/null

  done < <(foreach_initialized_submodule)
}

function check_for_unpushed_in_superproject(){
  check_superclean
  if [ $? -ne 0 ]; then
    log "ERROR: Superproject is not in a super clean state."
    return 1
  fi
}

## Check for modified content and uncommitted changes
check_clean || exit 1

## For for unmerged/unpushed changes
check_for_unpushed_in_superproject || exit 1
check_for_unpushed_in_submodules || exit 1
