#!/bin/bash
# STANDARD_RIFT_IO_COPYRIGHT
# Author(s): Austin Cormier
# Creation Date: 2014/05/22
#
# Do a recursive checkout of superproject and all initialized submodules.
#
# Usage: git-xcheckout [<checkout_arg>...]
#
# Args:
#  <checkout_args>:    Any argument or list of arguments that can be passed
#                      into git checkout at the superproject level.
#                      No <checkout_args> will prevent checkout from running at the top-level.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/git-common-functions.sh"

checkout_args="$@"
if [ "$checkout_args" == "" ]; then
  log "INFO: No xcheckout args provided.  Exiting."
  exit 0
fi

submodules="$(get_initialized_submodules)"

check_submodules_clean $submodules || exit 1
git check-superclean || exit 1

## Do the checkout at the supermodule if the branch/revision was specified.
## but to do this, everything should be sparkly clean.
log "INFO: Fetching all remotes."
git fetch --all || exit 1

git checkout $checkout_args
if [ $? -ne 0 ]; then
  log "ERROR: Failed to checkout $checkout_args"
  exit 1
fi

git xupdate
if [ $? -ne 0 ]; then
  log "CRITICAL: Failed to update submodules."
  exit 1
fi

