#!/bin/bash -e

# STANDARD_RIFT_IO_COPYRIGHT

# This script recursively shows the status of each submodule that is changed
# check that you are a top level
if [ ! -f .gitmodules ] ; then
    echo "$(basename $0) can only be executed from top (supermodule) level"
    exit 1
fi

if [ $# -ne 2 ]; then
    echo "args are start_hash end_hash"
    exit 1
fi
RE1="--- a/(.*)"
RE2="-Subproject commit (.*)"
RE3="\+Subproject commit (.*)"
git diff ${1}..${2} | while read line; do
    echo $line
    if [[ $line =~ $RE1 ]]; then
        module=${BASH_REMATCH[1]}
    elif [[ $line =~ $RE2 ]]; then
        start=${BASH_REMATCH[1]}
    elif [[ $line =~ $RE3 ]]; then
        end=${BASH_REMATCH[1]}
        pushd $module
        git diff ${start}..${end}
        popd
    fi
done
        
