#!/bin/bash
# 
# (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
#
# Author(s): Austin Cormier
# Creation Date: 2014/09/03
#
# This script force pushes committed changes in each submodule to corresponding
# submodule review repository.  Within Crucible, it is possible to select all
# the commits that were pushed into a single review.
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/git-common-functions.sh"

REVIEW_ROOT_REPO="git@git.eng.riftio.com:push_review.git"
REVIEW_SUBMODULE_REPO_BASE="git@git.eng.riftio.com:push_review_"

function push_review_in_submodules(){
  log "Pushing to review repos in the submodules"
  while read line; do
    pushd $line >/dev/null
      log "Pushing in submodule $line"
      git push -f "${REVIEW_SUBMODULE_REPO_BASE}${line}.git"
      if [ $? -ne 0 ]; then
        log "ERROR - Failed to push in submodule $line"
        log "PLEASE NOTIFY AUSTIN OR JEREMY"
      fi
    popd >/dev/null
  done < <(foreach_initialized_submodule)
}

function push_review_in_supermodule(){
  log "Pushing to review in the supermodule"
  git push -f "${REVIEW_ROOT_REPO}"
  if [ $? -ne 0 ]; then
    log "ERROR - Failed to push in supermodule."
    exit 1
  fi
}

push_review_in_submodules || exit 1
push_review_in_supermodule || exit 1

