#!/bin/bash -e

# 
# (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
#

# This script recursively shows the status of each submodule that is changed
# check that you are a top level
if [ ! -f .gitmodules ] ; then
    echo "$(basename $0) can only be executed from top (supermodule) level"
    exit 1
fi


echo "Diffs in supermodule"
meld .
echo ""

# Get the diff in each submodule
do_submodule_difftool() {
        name="$1"
        path="$2"
        toplevel="$3"
        cd "$toplevel/$path"
        if [[ $(git status -s) ]] ; then
                echo "Diffs in submodule $name"
                meld .
        fi
}

export -f do_submodule_difftool

git submodule foreach --quiet --recursive 'echo "$name $path $toplevel"' |
xargs -r -n3 -P20 bash -c 'do_submodule_difftool "$@"' do_submodule_difftool
