#!/bin/bash -e

# 
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# This script shows all changes in the super-module and all sub-modules in between two git super-module hashes

if [ $# -ne 2 ]; then
    echo "$(basename $0) args are start_hash end_hash"
    exit 1
fi

START=$1
END=$2
export START END

top_gitdir() {
    local d=$(git rev-parse --git-dir 2>/dev/null)
    [ $? -ne 0 ] && return

    d=$(readlink -m "${d}")
    d=${d%/.git*}
    echo "${d}"
}

toplevel=$(top_gitdir)
if [ -z "$toplevel" ]; then
    echo "Cannot locate top of git tree"
    exit 1
fi
export toplevel


echo "================================================== changes in SUPER-MODULE:"
cd $toplevel
git log ${START}..${END}

git submodule foreach --quiet '
    start=$(GIT_DIR=${toplevel}/.git git ls-tree $START $path | awk "{print \$3}");
    end=$(GIT_DIR=${toplevel}/.git git ls-tree $END $path | awk "{print \$3}");
    if [ $start == $end ]; then
            echo ================================================== NO changes in $path
    else
            echo ================================================== Changes in $path from $start to $end
            git log ${start}..${end};
    fi
'

