#!/bin/bash
# 
# (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
#
# Author(s): Varun Prasad
# Creation Date: 2015/12/22
#
# Helper script for invoking the mission control system test using the systest_wrapper
source $RIFT_INSTALL/usr/rift/systemtest/util/mano/mano_common.sh

SCRIPT_TEST="py.test -x -v -p no:cacheprovider -k 'not Teardown' \
            ${PYTEST_DIR}/mission_control/test_mission_control.py"

REBOOT_SCRIPT_TEST="py.test -x -v -p no:cacheprovider -k 'test_wait_for_launchpad_started or Teardown' \
                    ${PYTEST_DIR}/mission_control/test_mission_control.py"

test_prefix="mission_control_reload_systest"
test_cmd=""
repeat_system=1

# Parse commonline argument and set test variables
parse_args "${@}"

# Construct the test command based on the test variables
construct_test_comand

# Execute from pytest root directory to pick up conftest.py
cd "${PYTEST_DIR}"

test_rc=0
for i in $(seq ${repeat_system});
do
    echo "CYCLE: $i"
    eval ${test_cmd}
    test_rc=$?
    echo "DEBUG: Got test command rc: $test_rc"
    if [[ ${test_rc} -ne 0 ]]; then
        echo "Exiting with test_rc: $test_rc"
        break
     fi
done

# unit test XML files are converted to pretty printed format
pretty_print_junit_xml

exit ${test_rc}
